#settings
title: Entreprenurial Professional Podcasts
#images
logo_path: /images/logo.svg

socials:
  facebook: http://facebook.com
  youtube: http://youtube.com
  twitter: http://twitter.com
  linkedin: http://linkedin.com
